---
title: "Transformation Fréquence"
format: html
---


```{python imports}
from src.dags.helpers import connection_db
import dotenv
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn import preprocessing
import umap
import umap.plot

# Interactive mode
plt.ion()
```

```{python setup}
dotenv.load_dotenv(override=True)
```

```{python db_connection}
engine = connection_db()
df_raw = pd.read_sql("select * from dataset_train", engine)
```

```{python filter_rows}
df_raw = df_raw[df_raw.annee_visite <= 2021]
```

```{python filter_cols}
# df.columns.values.tolist()
df = df_raw[[
  "longueur_hors_tout",
  "jauge_oslo",
  "nombre_moteur",
  # "num_version",
  "puissance_administrative",
  # "sitrep_history",
  # "delai_visites",
  "age",
  "nombre_prescriptions_hist",
  "nombre_prescriptions_majeurs_hist"
]]
```

```{python deal_with_nan}
df.isna().sum()
df.jauge_oslo = df.jauge_oslo.fillna(df.jauge_oslo.mode().at[0])
df.nombre_moteur = df.nombre_moteur.fillna(df.nombre_moteur.mode().at[0])
df.puissance_administrative = df.puissance_administrative.fillna(df.puissance_administrative.mode().at[0])
```

```{python normalize_data}
scaler = preprocessing.StandardScaler()
df = scaler.fit_transform(df)
df = pd.DataFrame(df)
```

```{python umap}
mapper = umap.UMAP(random_state=42).fit(df)
```

```{python umap_plot}
umap.plot.points(mapper, labels=df_raw.cible, color_key={1: 'blue', 0: 'yellow'})

# hover_data = pd.DataFrame({
#   'index': df_raw.index,
#   'age':df_raw.age,
#   'nombre_prescriptions_hist': df_raw.nombre_prescriptions_hist
# })

p = umap.plot.points(mapper, values=df_raw.age, cmap='RdYlGn_r', background='white')
umap.plot.show(p)
p = umap.plot.points(mapper, values=df_raw.nombre_prescriptions_hist, cmap='RdYlGn_r', background='white')
umap.plot.show(p)
p = umap.plot.points(mapper, values=df_raw.longueur_hors_tout, cmap='RdYlGn_r', background='white')
umap.plot.show(p)
p = umap.plot.points(mapper, values=df_raw.jauge_oslo, cmap='RdYlGn_r', background='white')
umap.plot.show(p)
p = umap.plot.points(mapper, values=df_raw.nombre_moteur, cmap='RdYlGn_r', background='white')
umap.plot.show(p)
p = umap.plot.points(mapper, values=df_raw.puissance_administrative, cmap='RdYlGn_r', background='white')
umap.plot.show(p)

```

## Observations :

### Par rapport à la cible

4 îlots dont un grand et 3 petits (Grand = 1, puis dans notons les autres dans le sens horaire, jusqu'à 4)
Quelques valeurs ne sont rattachés à aucun îlot
L'ilôt le plus à gauche a des excroissances quasi indépendantes
Îlot 1 : Plus nous allons à gauche, plus nous sommes dans la cible. Pareil en allant vers le bas
Îlot 2 : Plus nous allons vers la droite, plus nous sommes dans la cible
Îlot 3 : Excroissance en bas est peu dans la cible
Îlot 4 : majoritairement hors de la cible

Nous observons égalmeent au nord deux mini îlots. Celui de gauche est rattachée à la cible.

### Par rapport à l'âge

Deux clusters de navires particulièrement âgés :

- 1 : excroissance au sud de l'îlot 1
- 2 : Entre îlots 3 et 4

On observe des dégradés très marqués sur chaque îlot, pas forcément orienté dans le même sens.


### Longueur hors tout

Dégradé du centre vers l'extérieur (des plus grands vers les plus petits).

- Cluster 3 qui est assez particulier : excroissance nord exclusivement avec
  de grands navires.
- On retrouve ça également sur une excroissance gauche de l'ilôt 4.
- Mini îlot nord-ouest de grands navires. Idem à l'est de l'ilôt 3.
- Les plus petits navires ne sont présents que sur l'ilôt 1 et légèrement 2

### Nombre prescriptions


* Îlot 1 et 4 sont sur des valeurs basses (quelques tâches plus claires)

* Îlot 2, dégradé léger de prescriptions (+ en + vers la droite)

* Îlot 3, valeurs assez importantes, concentration au nord de valeurs importantes

* Excroissance nord : dégradé du min (nord) au max (sud)
