version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/repo
    steps:
      - run:
          name: Trigger Netlify build
          command: |
            curl -X POST -d {} https://api.netlify.com/build_hooks/$NETLIFY_KEY

workflows:
  version: 2
  cron:
    triggers:
      - schedule:
          cron: "10 6,9,12,15,18,21 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
