SELECT DISTINCT GIN_NAVIRE_CATEG_NAVIG.NUM_IMMAT, GIN_NAVIRE_CATEG_NAVIG.NUM_VERSION, GIN_NAVIRE_CATEG_NAVIG.EFFECTIF_MINIMUM
FROM GIN_NAVIRE_CATEG_NAVIG
RIGHT JOIN (
	SELECT DISTINCT num_immat, MAX(num_version) num_version FROM GIN_NAVIRE_CATEG_NAVIG GROUP BY num_immat
) unique_version
ON unique_version.num_immat = GIN_NAVIRE_CATEG_NAVIG.num_immat AND unique_version.num_version = GIN_NAVIRE_CATEG_NAVIG.num_version)  debu
ON debu.NUM_IMMAT = NAVPRO.NAV_FLOTTEUR.NUM_IMMAT_FRANCAIS

