/* Requête qui extrait les données sur les catégories de navigations
 */

select GINA.GIN_NAVIRE_CATEG_NAVIG.*, GIN_CODE_CATEG_NAVIGATION.LIBELLE
from GINA.GIN_NAVIRE_CATEG_NAVIG
left join GIN_CODE_CATEG_NAVIGATION on GIN_CODE_CATEG_NAVIGATION.IDC_GIN_CATEG_NAVIGATION = GINA.GIN_NAVIRE_CATEG_NAVIG.IDC_GIN_CATEG_NAVIGATION
