name: Lint

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check code format against black
        uses: psf/black@stable
        with:
          src: "./src/dags/sitrep_web_postgre.py"
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Check import ordering against isort
        uses: isort/isort-action@master
        with:
          requirementsFiles: "requirements.txt"
          sortPaths: "./src/dags/sitrep_web_postgre.py"
      - name: Flake8 lint
        uses: py-actions/flake8@v2
        with:
          path: "./src/dags/sitrep_web_postgre.py"
